os: linux
language: cpp
compiler:
  - gcc
before_install: ./scripts/travis/install-deps.sh
install: ./scripts/travis/install-gtest.sh
script:
  - ./scripts/travis/cppcheck_wrapper.sh ./src
  - export BOOST_INCLUDES=/usr/include
  - export BOOST_LIBS=/usr/lib
  - ./autogen.sh && ./configure && make && make check
branches:
  only:
    - master
    - develop
