os:
  - linux
language: cpp
compiler:
  - gcc
  - clang
before_install: ./scripts/travis/install-deps.sh
install:
  - svn checkout http://googletest.googlecode.com/svn/trunk/ gtest
  - cd gtest && mkdir build && cd build && cmake .. && make
  - cd ../..
script:
  - ./scripts/travis/cppcheck_wrapper.sh ./src
  - ./autogen.sh && ./configure && make && make check
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - tommy@monetas.net
  email:
    on_success: change
    on_failure: always
