os:
  - linux
language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get install libboost-all-dev
install:
  - svn checkout http://googletest.googlecode.com/svn/trunk/ gtest
  - cd gtest && mkdir build && cd build && cmake .. && make
  - cd ../..
script:
  - ./autogen.sh && ./configure && make && make check
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - tommy@monetas.net
  email:
    on_success: change
    on_failure: always
