os: linux
language: cpp
compiler: gcc
before_install: ./scripts/travis/install-deps.sh
install:
  - ./scripts/travis/install-boost.sh
  - ./scripts/travis/install-opentxs.sh "${CXX}"
script:
  - ./scripts/travis/cppcheck_wrapper.sh ./src
  - mkdir build
  - cd build
  - cmake .. && make && make test
env:
  global:
    - BOOST_INCLUDES=/usr/local/include
    - BOOST_LIBS=/usr/local/lib
branches:
  only:
    - master
    - develop
